// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;
use crate::protos::common::android_log_constants::*;

pb_msg!(AndroidLogPacket {
    events: AndroidLogPacketLogEvent, msg, 1,
    stats: AndroidLogPacketStats, msg, 2,
});

pb_msg!(AndroidLogPacketStats {
    num_total: u64, primitive, 1,
    num_failed: u64, primitive, 2,
    num_skipped: u64, primitive, 3,
});

pb_msg!(AndroidLogPacketLogEvent {
    log_id: AndroidLogId, enum, 1,
    pid: i32, primitive, 2,
    tid: i32, primitive, 3,
    uid: i32, primitive, 4,
    timestamp: u64, primitive, 5,
    tag: String, primitive, 6,
    prio: AndroidLogPriority, enum, 7,
    message: String, primitive, 8,
    args: AndroidLogPacketLogEventArg, msg, 9,
});

pb_msg!(AndroidLogPacketLogEventArg {
    name: String, primitive, 1,
    int_value: i64, primitive, 2,
    float_value: f32, primitive, 3,
    string_value: String, primitive, 4,
});
